version: 0.1.{build}
install:
- nuget restore
build:
  publish_wap_xcopy: true
  verbosity: detailed
deploy:
- provider: FTP
  host: waws-prod-ch1-015.ftp.azurewebsites.windows.net
  protocol: ftp
  username: skepsiteste\skepsi
  password:
    secure: 5HD8gVFRbMV2/zB3djQQ+g==
  folder: /site/wwwroot
  application: Skepsi.Api.zip
  on:
    branch: develop
